"""add_conversation_id_and_rag_tracking

Revision ID: 1cfb79155de6
Revises: 0004
Create Date: 2026-05-23 20:47:47.229783

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1cfb79155de6'
down_revision: Union[str, None] = '0004'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_conversations_deleted_at', table_name='conversations', postgresql_where='(deleted_at IS NULL)')
    op.add_column('document_chunks', sa.Column('conversation_id', sa.UUID(), nullable=False))
    op.drop_index('ix_document_chunks_embedding', table_name='document_chunks', postgresql_with={'m': '16', 'ef_construction': '64'}, postgresql_using='hnsw')
    op.drop_index('ix_document_chunks_user_id_document_id', table_name='document_chunks')
    op.create_index(op.f('ix_document_chunks_conversation_id'), 'document_chunks', ['conversation_id'], unique=False)
    op.create_foreign_key(None, 'document_chunks', 'conversations', ['conversation_id'], ['id'], ondelete='CASCADE')
    op.add_column('documents', sa.Column('conversation_id', sa.UUID(), nullable=False))
    op.drop_index('ix_documents_user_id_status', table_name='documents')
    op.create_index(op.f('ix_documents_conversation_id'), 'documents', ['conversation_id'], unique=False)
    op.create_foreign_key(None, 'documents', 'conversations', ['conversation_id'], ['id'], ondelete='CASCADE')
    op.add_column('messages', sa.Column('rag_used', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('messages', sa.Column('relevance_score', sa.Float(), nullable=True))
    op.add_column('messages', sa.Column('retrieved_chunk_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.drop_constraint('uq_users_clerk_user_id', 'users', type_='unique')
    op.create_index(op.f('ix_users_clerk_user_id'), 'users', ['clerk_user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_clerk_user_id'), table_name='users')
    op.create_unique_constraint('uq_users_clerk_user_id', 'users', ['clerk_user_id'])
    op.drop_column('messages', 'retrieved_chunk_ids')
    op.drop_column('messages', 'relevance_score')
    op.drop_column('messages', 'rag_used')
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.drop_index(op.f('ix_documents_conversation_id'), table_name='documents')
    op.create_index('ix_documents_user_id_status', 'documents', ['user_id', 'status'], unique=False)
    op.drop_column('documents', 'conversation_id')
    op.drop_constraint(None, 'document_chunks', type_='foreignkey')
    op.drop_index(op.f('ix_document_chunks_conversation_id'), table_name='document_chunks')
    op.create_index('ix_document_chunks_user_id_document_id', 'document_chunks', ['user_id', 'document_id'], unique=False)
    op.create_index('ix_document_chunks_embedding', 'document_chunks', ['embedding'], unique=False, postgresql_with={'m': '16', 'ef_construction': '64'}, postgresql_using='hnsw')
    op.drop_column('document_chunks', 'conversation_id')
    op.create_index('ix_conversations_deleted_at', 'conversations', ['deleted_at'], unique=False, postgresql_where='(deleted_at IS NULL)')
    # ### end Alembic commands ###
